# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: pgcrypto 0.4.0 ruby lib

Gem::Specification.new do |s|
  s.name = "pgcrypto"
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Flip Sasser"]
  s.date = "2014-08-24"
  s.description = "\n      PGCrypto is an ActiveRecord::Base extension that allows you to asymmetrically\n      encrypt PostgreSQL columns with as little trouble as possible. It's totally\n      freaking rad.\n    "
  s.email = "flip@x451.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    ".rspec",
    ".simplecov",
    "CHANGES.md",
    "Gemfile",
    "Guardfile",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/active_record/connection_adapters/pgcrypto_adapter.rb",
    "lib/active_record/connection_adapters/pgcrypto_adapter/rails_3.rb",
    "lib/active_record/connection_adapters/pgcrypto_adapter/rails_4.rb",
    "lib/pgcrypto.rb",
    "lib/pgcrypto/adapter.rb",
    "lib/pgcrypto/column.rb",
    "lib/pgcrypto/column_converter.rb",
    "lib/pgcrypto/generators/base_generator.rb",
    "lib/pgcrypto/generators/install/USAGE",
    "lib/pgcrypto/generators/install/install_generator.rb",
    "lib/pgcrypto/generators/install/templates/initializer.rb",
    "lib/pgcrypto/generators/install/templates/migration.rb",
    "lib/pgcrypto/generators/upgrade/USAGE",
    "lib/pgcrypto/generators/upgrade/templates/migration.rb",
    "lib/pgcrypto/generators/upgrade/upgrade_generator.rb",
    "lib/pgcrypto/has_encrypted_column.rb",
    "lib/pgcrypto/key.rb",
    "lib/pgcrypto/key_manager.rb",
    "lib/pgcrypto/railtie.rb",
    "lib/pgcrypto/table.rb",
    "lib/pgcrypto/table_manager.rb",
    "lib/tasks/pgcrypto.rake",
    "pgcrypto.gemspec",
    "spec/lib/pgcrypto_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/private.key",
    "spec/support/private.password.key",
    "spec/support/public.key",
    "spec/support/public.password.key"
  ]
  s.homepage = "http://github.com/Plinq/pgcrypto"
  s.rubygems_version = "2.4.1"
  s.summary = "A transparent ActiveRecord::Base extension for encrypted columns"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

