# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "pgcrypto"
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Flip Sasser"]
  s.date = "2012-03-02"
  s.description = "\n      PGCrypto is an ActiveRecord::Base extension that allows you to asymmetrically\n      encrypt PostgreSQL columns with as little trouble as possible. It's totally\n      freaking rad.\n    "
  s.email = "flip@x451.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    ".rspec",
    "CHANGES",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/pgcrypto.rb",
    "lib/pgcrypto/active_record.rb",
    "lib/pgcrypto/arel.rb",
    "lib/pgcrypto/key.rb",
    "lib/pgcrypto/table_manager.rb",
    "pgcrypto.gemspec"
  ]
  s.homepage = "http://github.com/Plinq/pgcrypto"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "A transparent ActiveRecord::Base extension for encrypted columns"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

