# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "pgcrypto"
  s.version = "0.3.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Flip Sasser"]
  s.date = "2012-08-22"
  s.description = "\n      PGCrypto is an ActiveRecord::Base extension that allows you to asymmetrically\n      encrypt PostgreSQL columns with as little trouble as possible. It's totally\n      freaking rad.\n    "
  s.email = "flip@x451.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    ".rspec",
    ".simplecov",
    "CHANGES.md",
    "Gemfile",
    "Guardfile",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/generators/pgcrypto/install/USAGE",
    "lib/generators/pgcrypto/install/install_generator.rb",
    "lib/generators/pgcrypto/install/templates/initializer.rb",
    "lib/generators/pgcrypto/install/templates/migration.rb",
    "lib/pgcrypto.rb",
    "lib/pgcrypto/active_record.rb",
    "lib/pgcrypto/arel.rb",
    "lib/pgcrypto/column.rb",
    "lib/pgcrypto/key.rb",
    "lib/pgcrypto/table_manager.rb",
    "pgcrypto.gemspec",
    "spec/lib/pgcrypto_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/private.key",
    "spec/support/private.password.key",
    "spec/support/public.key",
    "spec/support/public.password.key"
  ]
  s.homepage = "http://github.com/Plinq/pgcrypto"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "A transparent ActiveRecord::Base extension for encrypted columns"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, ["= 3.2.7"])
      s.add_runtime_dependency(%q<big_spoon>, [">= 0.2.1"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, ["= 3.2.7"])
      s.add_dependency(%q<big_spoon>, [">= 0.2.1"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, ["= 3.2.7"])
    s.add_dependency(%q<big_spoon>, [">= 0.2.1"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

